nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://localhost:3000$', '^http://127.0.0.1:3000$']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Access-Control-Request-Method', 'Access-Control-Request-Headers']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['^http://localhost:3000$', '^http://127.0.0.1:3000$']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Access-Control-Request-Method', 'Access-Control-Request-Headers']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
